### PR TITLE
Bugfix #18: ReferenceError - process is not defined

### PR DESCRIPTION
**Pull request by ionleu**
Provided a fix for https://github.com/jrgarciadev/react-iconly/issues/18 issue. 
This is a critical issue that seems to appear on all projects that are using `react-scripts@5` and up.

Tested locally and works as expected. Attached screenshots of the example view and tests.
Example view

Screenshot 2023-04-09 at 11 41 34 AM

### CODE REVIEW

**Comment by ionleu** [comment]
@jrgarciadev can you please take a look?  😅
Thanks

**Review by jrgarciadev — APPROVED** [review]
Huge thanks @ionleu 🙏🏻

**Comment by jrgarciadev** [comment]
Btw @ionleu would you like to change microbundle-ctrl by https://tsup.egoist.dev/ ?

**Comment by ionleu** [comment]
@jrgarciadev I'll try to look into it this weekend.😅

**Pull request merged**
